var NAVTREEINDEX4 =
{
"page-sound-generation.html#how-to-play-score":[0,4,3],
"page-sound-generation.html#implementing-player-gui":[0,4,5],
"page-sound-generation.html#page-sound-generation-overview":[0,4,0],
"page-sound-generation.html#playback-summary":[0,4,1],
"page-tasks.html":[0,5],
"page-tasks.html#gui-interaction":[0,5,0],
"page-tasks.html#task-data-entry":[0,5,1,6],
"page-tasks.html#task-drag-view":[0,5,1,0],
"page-tasks.html#task-move-handler":[0,5,1,5],
"page-tasks.html#task-move-object":[0,5,1,4],
"page-tasks.html#task-only-clicks":[0,5,1,1],
"page-tasks.html#task-selection":[0,5,1,2],
"page-tasks.html#task-selection-rectangle":[0,5,1,3],
"page-tasks.html#tasks-overview":[0,5,1],
"pages.html":[],
"todo.html":[6]
};
